# Generated by Django 5.0.4 on 2024-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn_vote_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_opened',
            field=models.BooleanField(default=False),
        ),
    ]
