# Generated by Django 5.0.4 on 2024-05-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn_vote_system', '0002_vote_vote_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='number_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VoteResponse',
        ),
    ]
