# Generated by Django 5.0.4 on 2024-05-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn_vote_system', '0003_voteoption_number_votes_delete_voteresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteTokenUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esn_vote_system.token')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esn_vote_system.vote')),
            ],
        ),
    ]
