# Generated by Django 5.0.4 on 2024-05-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn_vote_system', '0005_adminkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='datetime_vote_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
